/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package institute;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Ironman
 */
public class forgot extends javax.swing.JFrame {
     connection C=new connection();

    /**
     * Creates new form forgot
     */
    public forgot() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        secans = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        secque = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(980, 580));
        setMinimumSize(new java.awt.Dimension(980, 580));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("UserName");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 42, 156, 37);
        getContentPane().add(username);
        username.setBounds(354, 97, 230, 31);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText(" Security Question");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(273, 252, 144, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Security Answer");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(273, 301, 144, 22);
        getContentPane().add(secans);
        secans.setBounds(470, 301, 216, 29);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(429, 458, 72, 38);

        secque.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        secque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your building name?", "What is your favorite book name?", "What are your hobbies?", "What is your favorite color?", "What is your dream job?" }));
        getContentPane().add(secque);
        secque.setBounds(470, 250, 216, 29);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yash\\Music\\All Documents\\project folder\\05.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 980, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if(username.getText().isEmpty() && secans.getText().isEmpty())
        {
             JOptionPane.showMessageDialog(null,"Please enter all details !! ","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
         try
       {
         
         String qry="select * from sign_in where userid='"+username.getText()+"' and secque='"+secque.getSelectedItem()+"'  and secans='"+secans.getText()+"'";
        // JOptionPane.showMessageDialog(this,qry);
         
         C.rs=C.stmt.executeQuery(qry);
         if(C.rs.next())
         {
            JOptionPane.showMessageDialog(null,"Login Successfully");
             Menu m=new Menu();
                   m.setVisible(true);
                   
         }
         else
         {
            JOptionPane.showMessageDialog(null,"Invalid username and password");
            username.setText(null);
            secans.setText(null);
         }
         if(username.getText().isEmpty())
         {
             JOptionPane.showMessageDialog(null,"Please enter username ","Error",JOptionPane.ERROR_MESSAGE);
            return;
         }
          if(secans.getText().isEmpty())
         {
             JOptionPane.showMessageDialog(null,"Please enter Security answer ","Error",JOptionPane.ERROR_MESSAGE);
            return;
         }
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(this,e.toString());
           
       }
         
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField secans;
    private javax.swing.JComboBox<String> secque;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
